version: '1.0'
name: master-pipeline
displayName: MasterPipeline
triggers:
  trigger: auto
  push:
    branches:
      include:
        - master
stages:
  - name: compile
    displayName: 编译
    strategy: naturally
    trigger: auto
    steps:
      - step: build@golang
        name: build_golang
        displayName: Golang 构建
        golangVersion: 1.18
        commands:
          - GOOS=windows GOARCH=amd64 go build -o output/YzLauncher-windows.exe main.go
        artifacts:
          - name: BUILD_ARTIFACT
            path:
              - ./output
        strategy: {}
      - step: publish@general_artifacts
        name: publish_general_artifacts
        displayName: 上传制品
        dependArtifact: BUILD_ARTIFACT
        artifactName: output
        strategy: {}
        dependsOn: build_golang
